name: tonie_shuffle
description: A command-line utility to shuffle Creative Tonie playlists.
version: 1.1.0
homepage: https://github.com/cachapa/tonie_shuffle

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.0
  http: ^0.12.0+3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
